services:
  build:
    init: true
    image: w4bo/python:1.0.4
    volumes:
      - ./:/data
    command: bash -c "cd /data && chmod +x ./utils/build.sh && ./utils/build.sh"

  publish:
    init: true
    image: w4bo/quarto-slides:1.0.24
    hostname: publish
    container_name: publish
    ports:
      - "6778:6778"
    volumes:
      - ./:/data
    command: bash -c "chmod +x /data/publish.sh && /data/publish.sh"